version: '3'
services:
  mongo:
    container_name: 'mongo'
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
      - ./Makefile:/Makefile
      - ./.env:/.env
      - ./export:/export
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
